@apiRootUrl = https://localhost:7049
@apiUrl = {{apiRootUrl}}/api

### get health

GET {{apiRootUrl}}/healthz

### get exception

GET {{apiUrl}}/exception
Accept: application/json

### Add more API requests
