version: '3.5'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    command: /bin/bash ./entrypoint.sh
    ports:
      - 1434:1433 # login with sa:P@55w0rd
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=P@55w0rd"
      - "MSSQL_PID=Developer"
    volumes:
      - sqldata:/var/opt/mssql
      - ./build/db/docker-entrypoint.sh:/entrypoint.sh
      - ./build/db/docker-db-init.sh:/db-init.sh
      - ./build/db/concord.sql:/db-init.sql

volumes:
  sqldata:
    driver: local
