#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

## stash all un-staged files before running the tasks
##git stash -k -q

## run all tasks
#husky run

### run all tasks with group: 'group-name'
#husky run --group group-name

## run task with name: 'task-name'
#husky run --name task-name

## pass hook arguments to task
#husky run --args "$1" "$2"

## or put your custom commands -------------------
#echo 'Husky.Net is awesome!'

dotnet husky run